In [1]:
# Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading dataset
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,3].values

In [3]:
# Missing Data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [4]:
# Encoding
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
ct = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X), dtype=np.float)
labelencoder_Y = LabelEncoder()
y = labelencoder_Y.fit_transform(y)

In [142]:
# Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [149]:
testing = np.array(X_train, dtype=np.int)
testing

array([[    0,     1,     0,    40, 63777],
       [    1,     0,     0,    37, 67000],
       [    0,     0,     1,    27, 48000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    48, 79000],
       [    0,     0,     1,    38, 61000],
       [    1,     0,     0,    44, 72000],
       [    1,     0,     0,    35, 58000]])

In [150]:
# Feature scaling
from sklearn.preprocessing import StandardScaler, MinMaxScaler
scaler = MinMaxScaler()
testing = scaler.fit_transform(testing)
testing

array([[0.        , 1.        , 0.        , 0.61904762, 0.50893548],
       [1.        , 0.        , 0.        , 0.47619048, 0.61290323],
       [0.        , 0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.52380952, 0.12903226],
       [1.        , 0.        , 0.        , 1.        , 1.        ],
       [0.        , 0.        , 1.        , 0.52380952, 0.41935484],
       [1.        , 0.        , 0.        , 0.80952381, 0.77419355],
       [1.        , 0.        , 0.        , 0.38095238, 0.32258065]])

In [147]:
scaler.mean_

array([5.0000000e-01, 1.2500000e-01, 3.7500000e-01, 3.8375000e+01,
       6.2597125e+04])

In [154]:
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train.reshape(-1,1))
y_train

array([[ 0.77459667],
       [ 0.77459667],
       [ 0.77459667],
       [-1.29099445],
       [ 0.77459667],
       [-1.29099445],
       [-1.29099445],
       [ 0.77459667]])