In [44]:
%config IPCompleter.greedy=True
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [78]:
dataset = pd.read_csv('Data.csv')

In [79]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,3].values

In [80]:
from sklearn.impute import SimpleImputer

In [81]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [82]:
imputer = imputer.fit(X[:, 1:3])

In [83]:
X[:, 1:3] = imputer.transform(X[:, 1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [84]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [85]:
labelencoder_Y = LabelEncoder()
y = labelencoder_Y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [87]:
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [95]:
T_X = X[:, 0:1]
T_X

array([[0],
       [2],
       [1],
       [2],
       [1],
       [0],
       [2],
       [0],
       [1],
       [0]], dtype=object)

In [103]:
onehotencoder = OneHotEncoder(categories=[[0,1,2], ['auto'], ['auto']], sparse=False)
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [104]:
X = onehotencoder.fit_transform(X)

ValueError: Found unknown categories [35.0, 37.0, 38.0, 38.77777777777778, 40.0, 44.0, 48.0, 50.0, 27.0, 30.0] in column 1 during fit

In [98]:
T_X

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])